#dist: xenial
#language: python
#cache: pip
#
#jobs:
#  include:
#    - python: 3.6
#      env: TENSORFLOW_V=1.15.3 KERAS_V=2.2.5
#      script:
#        - ./run_tests.sh
#
#    - python: 3.7
#      env: TENSORFLOW_V=2.2.0 KERAS_V=2.3.1
#      script:
#        - ./run_tests.sh
#
#    - python: 3.7
#      env: TENSORFLOW_V=2.2.0 KERAS_V=2.3.1
#      script:
#        - (pycodestyle --ignore=C0330,C0415,E203,E231,W503 --max-line-length=120 art || exit 0)
#        - (pylint --disable=C0330,C0415,E203,E1136 -rn art || exit 0)
#        - (mypy art || exit 0)
#        - py.test --pep8 -m pep8
#
#before_install:
#  - sudo apt-get -y -q install ffmpeg libavcodec-extra
#  - sed -i "s/^tensorflow$/tensorflow==${TENSORFLOW_V}/" requirements.txt
#  - sed -i "s/^keras$/keras==${KERAS_V}/" requirements.txt
#
#install:
#  - python -m pip install --upgrade pip==20.1.1 setuptools wheel
#  - pip install -q pylint pycodestyle
#  - pip install -q -r requirements.txt
#  - pip list
