dist: xenial
language: python
env:
  - KERAS_BACKEND=tensorflow TENSORFLOW_V=1.15.0 KERAS_V=2.2.5
  - KERAS_BACKEND=tensorflow TENSORFLOW_V=2.1.0 KERAS_V=2.3.1
python:
   - "3.6"
matrix:
  include:
    - python: 3.6
      env: KERAS_BACKEND=tensorflow TENSORFLOW_V=1.15.0 KERAS_V=2.2.5
      script:
        - (pycodestyle --max-line-length=120 art || exit 0) && (pylint --disable=C0415,E1136 -rn art || exit 0)
        - py.test --pep8 -m pep8

before_install:
  - sed -i "s/tensorflow/tensorflow==${TENSORFLOW_V}/" test_requirements.txt
  - sed -i "s/keras/keras==${KERAS_V}/" test_requirements.txt

install:
  - python -m pip install --upgrade pip==19.3.1 setuptools wheel
  - pip install -q -r requirements.txt
  - pip install --upgrade --force-reinstall mxnet
  - pip install -q -r test_requirements.txt
  - pip install -q pylint pycodestyle
  - pip install -q torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip list

script:
  - ./run_tests.sh
