python noise_predictor_training.py --model resnet18 \
    --num_classes 4 \
    --list pixelattack_spatialtransformation_squareattack_autopgd \
    --lr-schedule piecewise \
    --norm l_inf \
    --epsilon 8 \
    --epochs 110 \
    --labelsmooth \
    --labelsmoothvalue 0.3 \
    --fname auto \
    --optimizer 'momentum' \
    --lr-max 0.05\
    --weight-decay 2e-4 \
    --batch-size 128 \
    --BNeval 